### ISSUE TITLE
使用官网的demon BrnSelectedListActionSheet 报错

### ISSUE THREAD

**Issue by an-bad-apple** [LianjiaTech/bruno#515]
## 问题提交

标题格式：[BUG]: 问题简介

The following _TypeError was thrown building:
type '(int, String) => String' is not a subtype of type '(int, String?) => dynamic'

When the exception was thrown, this was the stack: 
#0      _BrnActionSheetSelectedItemListState.build.<anonymous closure> (package:bruno/src/components/actionsheet/brn_selected_list_action_sheet.dart:474:49)
#1      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:490:22)
#2      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:828:28)
#3      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:758:67)
#4      Iterable.forEach (dart:core/iterable.dart:347:35)
#5      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:805:24)
#6      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:734:7)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3685:15)
<img width="846" alt="image" src="https://github.com/LianjiaTech/bruno/assets/26055389/7ad37add-913e-4ea0-997d-2a80af1d5df0">
<img width="1283" alt="image" src="https://github.com/LianjiaTech/bruno/assets/26055389/e6e00a4b-fc78-461c-96f6-4418dcf25cdb">
<img width="700" alt="image" src="https://github.com/LianjiaTech/bruno/assets/26055389/935bae0a-42b6-40e0-b8f2-2785e4bd9634">

**Comment by luyanlovelele** [comment]
itemTitleBuilder: (int index, String? entity) {
          return entity;
        },
