### ISSUE TITLE
[BUG]: BrnTabBar 设置 showMore: true， 运行时报错

### ISSUE THREAD

**Issue by lemos1235** [LianjiaTech/bruno#98]
**1、BUG 描述**

BrnTabBar 设置 showMore: true 运行时报错

**2、复现步骤**

点击展开时报错 A RenderFlex overflowed by 199413 pixels on the bottom ，见附图

```dart
Scaffold(
      appBar: BrnAppBar(
        brightness: Brightness.dark,
        leading: BrnBackLeading(
          child: FlutterLogo(),
        ),
        title: Text("HELLO"),
      ),
      body: Column(
        children: [
          BrnTabBar(
            tabHeight: AppBar().preferredSize.height,
            tabs: [
              BadgeTab(text: "需求1"),
              BadgeTab(text: "需求2"),
            ],
            showMore: true,
            controller: _tabController,
            onTap: (state, index) {
              // state.refreshBadgeState(index);
            },
          ),
        ],
      ),
    );
```

**3、期望行为**

不报错

**4、运行环境**

flutter 2.8.1

* 运行设备
android similutar Pixel5
* 系统
windows11
* Bruno 版本
null-safe
* Flutter Doctor 信息
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.466], locale
    zh-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)

**5、附加信息**

![image](https://user-images.githubusercontent.com/23135552/153544041-d24f420e-fed3-45eb-b483-3ad12e323dfc.png)

**Comment by violinday** [comment]
@lemos1235
感谢反馈~
经过排查代码，截图中的 overflowed 问题应该是”其他问题报错后，红屏展示 Error 信息时展示不下溢出“导致的。可以补充下纤细的报错日志吗 :)

**Comment by lemos1235** [comment]
具体的错误日志
```
Performing hot restart...
Syncing files to device Android SDK built for x86...
../../AppData/Local/Pub/Cache/git/bruno-5401fba5d7e44eb16f2f33baa9b24a8997fc6180/lib/src/components/text/brn_expandable_text.dart:77:20: Warning: Operand of null-aware operation '!' has type 'bool' which excludes null.
          if (this._expanded!) {
                   ^
../../AppData/Local/Pub/Cache/git/bruno-5401fba5d7e44eb16f2f33baa9b24a8997fc6180/lib/src/components/text/brn_expandable_text.dart:136:32: Warning: Operand of null-aware operation '!' has type 'bool' which excludes null.
            widget.onExpanded!(_expanded!);
                               ^
Restarted application in 2,796ms.

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Container(Alignment.center, bg: BoxDecoration(color: Color(0xfff8f8f8), borderRadius: BorderRadius.circular(4.0)), constraints: BoxConstraints(w=-19.0, h=32.0; NOT NORMALIZED), dirty):
BoxConstraints has a negative minimum width.

The offending constraints were: BoxConstraints(w=-19.0, h=32.0; NOT NORMALIZED)
The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///C:/Users/admin/StudioProjects/bruno_widgets/lib/main.dart:14:12
When the exception was thrown, this was the stack: 
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:516:9)
#1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:545:9)
#2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:564:6)
#3      new ConstrainedBox (package:flutter/src/widgets/basic.dart:2354:27)
#4      Container.build (package:flutter/src/widgets/container.dart:428:17)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4827:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735:5)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
...     Normal element mounting (21 frames)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#31     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#32     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (10 frames)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#43     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#44     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (16 frames)
#60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#61     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#62     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (101 frames)
#163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#164    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#165    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (52 frames)
#217    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#218    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
#220    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5845:32)
#221    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#222    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#223    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#224    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#225    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#226    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#227    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#228    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#229    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#230    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#231    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#235    _invoke (dart:ui/hooks.dart:151:10)
#236    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#237    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Container(Alignment.center, bg: BoxDecoration(color: Color(0x140984f9), borderRadius: BorderRadius.circular(4.0)), constraints: BoxConstraints(w=-19.0, h=32.0; NOT NORMALIZED), dirty):
BoxConstraints has a negative minimum width.

The offending constraints were: BoxConstraints(w=-19.0, h=32.0; NOT NORMALIZED)
The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///C:/Users/admin/StudioProjects/bruno_widgets/lib/main.dart:14:12
When the exception was thrown, this was the stack: 
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:516:9)
#1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:545:9)
#2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:564:6)
#3      new ConstrainedBox (package:flutter/src/widgets/basic.dart:2354:27)
#4      Container.build (package:flutter/src/widgets/container.dart:428:17)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4827:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735:5)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
...     Normal element mounting (21 frames)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#31     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#32     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (10 frames)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#43     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#44     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (16 frames)
#60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#61     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#62     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (101 frames)
#163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#164    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#165    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (52 frames)
#217    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#218    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
#220    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5845:32)
#221    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#222    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#223    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#224    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#225    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#226    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#227    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#228    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#229    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#230    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#231    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#235    _invoke (dart:ui/hooks.dart:151:10)
#236    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#237    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================

======== Exception caught by rendering library =====================================================
The following assertion was thrown during layout:
A RenderFlex overflowed by 199513 pixels on the bottom.

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///C:/Users/admin/StudioProjects/bruno_widgets/lib/main.dart:14:12
The overflowing RenderFlex has an orientation of Axis.vertical.
The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and black striped pattern. This is usually caused by the contents being too big for the RenderFlex.

Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the RenderFlex to fit within the available space instead of being sized to their natural size.
This is considered an error condition because it indicates that there is content that cannot be seen. If the content is legitimately bigger than the available space, consider clipping it with a ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex, like a ListView.

The specific RenderFlex in question is: RenderFlex#3ef19 OVERFLOWING
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=392.7, h=550.9)
...  size: Size(392.7, 550.9)
...  direction: vertical
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: center
...  verticalDirection: down
◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
====================================================================================================
```

**Comment by violinday** [comment]
感谢提供问题日志，已确认该问题是由于内部 Size 计算导致的，
问题原因在这里:
`The offending constraints were: BoxConstraints(w=-19.0, h=32.0; NOT NORMALIZED)`
宽度约束为负数，导致debug 模式下异常日志溢出。Release 模式下不会产生这个问题。在即将发布的版本中会优化这个问题

**Comment by wiy2015** [comment]
3.3.0重现
